name: Mise à jour quotidienne des prix de l’essence

permissions:
  contents: write

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install requests pandas openpyxl
          
      - name: Run fetch script
        run: python3 fetch_regie_essence.py

      - name: Commit CSV if changed
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/regie_essence_quebec.csv

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily update of fuel prices"
            git push
          fi
